# Generated by Django 3.2.10 on 2022-02-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('Roll_no', models.IntegerField()),
                ('City', models.CharField(max_length=20)),
            ],
        ),
    ]
